name: "Git Diff"
description: "GitHub Action to get difference in pull requests."

inputs:
  github-token:
    description: "The GitHub token used to create an authenticated client"
    default: ${{ github.token }}
    required: false

outputs:
  changed: # id of output
    description: "The changed files"

runs:
  using: "node12"
  main: "dist/index.js"
